spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/eatmotion
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  redis:
    port: 6379
    host: localhost

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
secret:
  token:
    key: asdfdfea!dfeasdfe

server:
  port: 8081
#  servlet:
#    context-path: /api
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

api:
  id: 5eu50cwdvd
  secret: g42Rfm6qnHA2A8E2Ypjmeo4A7Hq8c8eVXYlAh3Un
  secretKey: WWJtb3lmRHZuYmxjbXRFT2xocmZZREtRSFFReUxVUXM=